# Generated by Django 4.2.4 on 2023-08-10 16:15

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                ("name", models.CharField(max_length=100)),
                (
                    "p_pic",
                    models.ImageField(
                        storage=django.core.files.storage.FileSystemStorage(
                            location=""
                        ),
                        upload_to="",
                    ),
                ),
                ("brand", models.CharField(max_length=100)),
                ("demand", models.PositiveBigIntegerField()),
                ("year", models.PositiveIntegerField()),
                ("engine", models.PositiveIntegerField(help_text="in Cc")),
                ("variant", models.CharField(max_length=25)),
                (
                    "mileage",
                    models.PositiveIntegerField(
                        blank=True, help_text="in kM", null=True
                    ),
                ),
                ("features", models.TextField(max_length=200)),
                ("insured", models.CharField(max_length=3)),
                ("my", models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
