# Generated by Django 4.2.4 on 2023-08-10 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("showroom", "0002_remove_profile_brand_remove_profile_demand_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="contact",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
