# Generated by Django 4.2.4 on 2023-08-10 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("showroom", "0003_profile_contact_alter_profile_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="price",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
