# Generated by Django 4.2.4 on 2023-08-11 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("showroom", "0004_profile_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="insured",
            field=models.CharField(
                choices=[("yes", "INSURED "), ("no", "NOT INSURED ")], max_length=3
            ),
        ),
    ]
