# Generated by Django 4.2.7 on 2023-11-20 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("showroom", "0005_alter_profile_insured"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="dat",
        ),
    ]
