# Generated by Django 4.2.7 on 2023-11-20 15:32

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("showroom", "0006_remove_profile_dat"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="bid_end_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="bid_start_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 11, 20, 15, 32, 49, 694328, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
    ]
